### ISSUE TITLE
Pure python version missing hello.py file

### ISSUE THREAD

**Issue by FMalerba** [scikit-build/scikit-build-sample-projects#11]
Am I wrong or is the `projects/hello-pure/hello` folder missing a hello.py file that defines the two functions `hello` and `elevation`?

**Comment by jcfr** [comment]
Thanks for your interest in scikit-build 

The functions are implemented in the file hello/__init__.py

**Comment by FMalerba** [comment]
Thank you so much I totally missed them. Could you help me out with something else that lead me here while I was trying to solve it?
In [this](https://github.com/FMalerba/skbuild_test) repo there is a small sample of some test code where I want to build a python package using skbuild. As you can see it has a nested structure where `lib.py` is imported by `skbuild_test.py`. When running `python setup.py install` I get the following skbuild error:

`
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    packages=['lib', 'lib.skbuild_test_lib'],
  File "venv\lib\site-packages\skbuild\setuptools_wrap.py", line 625, in setup
    cmake_source_dir, skbuild_kw['cmake_install_dir'])
  File "venv\lib\site-packages\skbuild\setuptools_wrap.py", line 757, in _classify_installed_files
    install_root, to_platform_path(path)))
skbuild.exceptions.SKBuildError:
  CMake-installed files must be within the project root.
    Project Root  : skbuild_test\_skbuild\win-amd64-3.7\cmake-install
    Violating File: skbuild_test\_skbuild\win-amd64-3.7\cmake-install\skbuild_test\__init__.py
`

Do you have any idea what I'm doing wrong?
