### ISSUE TITLE
hello-pybind11 example doesn't work

### ISSUE THREAD

**Issue by ktbarrett** [scikit-build/scikit-build-sample-projects#5]
https://github.com/scikit-build/scikit-build-sample-projects/blob/9888346e8db29ce7e5ad3c5fd6f38c4bbb89df1c/projects/hello-pybind11/wrap/__init__.py#L4

This isn't valid syntax. 

`pip install .` doesn't work, I have to do `python setup.py install` to get it to run.

```
Processing /home/kaleb/dev/scikit-build-sample-projects/projects/hello-pybind11
    ERROR: Command errored out with exit status 1:
     command: /home/kaleb/miniconda3/envs/py38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ya25c9_i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ya25c9_i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-ya25c9_i/pip-egg-info
         cwd: /tmp/pip-req-build-ya25c9_i/
    Complete output (7 lines):
    running egg_info
    creating /tmp/pip-req-build-ya25c9_i/pip-egg-info/hello_pybind11.egg-info
    writing /tmp/pip-req-build-ya25c9_i/pip-egg-info/hello_pybind11.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-req-build-ya25c9_i/pip-egg-info/hello_pybind11.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-req-build-ya25c9_i/pip-egg-info/hello_pybind11.egg-info/top_level.txt
    writing manifest file '/tmp/pip-req-build-ya25c9_i/pip-egg-info/hello_pybind11.egg-info/SOURCES.txt'
    error: package directory 'hello' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Even after installation the installed package doesn't seem to work. If I import the hello package, there is nothing in it. The log of the build command shows it's only installing the egg?

I was hoping this example would be a good example because of the issues I've seen in scikit-build/scikit-build#424.

**Comment by kratsg** [comment]
Just to note that I'm also running into this issue and struggling to get `scikit-build` working correctly for me (both regular installs as well as editable installs). I am making a library + some other dynamic so's that it links to privately. Can provide more details if there are suggestions on how to get it working...

**Comment by henryiii** [comment]
I've tried running the example and it is quite broken. It also seems much more complex than a hello world example should be - things like CMake configs are a bit overkill, and it should use pyproject.toml to setup and install pybind11 as well as scikit-build. I can take a stab at cleaning it up. I take it there's no CI running to test the examples? The invalid syntax mentioned above is one case where it could never have worked.

One thing would really help me clear this up, and I thought I used to know this - how do you specify the "main" directory as an install target? One that will get placed in the wheel without going to the data directory (which is for shared libs and such).

**Comment by henryiii** [comment]
Okay, the following works:

* Change the `wrap` directory into `hello` (or `src/hello` + `package_dir={'': 'src'}`), so setuptools can find and install from it
    - Edit line in `CMakeLists.txt` to point at this directory instead of `wrap`, as well
* Change the invalid syntax into `from ._hello import hello, return_two` (which doesn't double nest, as well)
* Add a pyproject.toml with `requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja"]` under `[build-system]`.

I'll clean up a bit and make a PR in the near future.

**Comment by ktbarrett** [comment]
In addition to the example provided here that will be more of a simple pybind11 project; meaning it is focused mainly on being a Python project, the C sources are not mean to be re-used. I'm also working on a "more advanced" [example project](https://github.com/ktbarrett/hello-pybind11-2) that I'm not sure fits in this repo. It is a C++ library project that is system installable, but uses pybind11 and scikit-build to wrap that C++ project for use with Python as well. Tests will be in both C++ and Python.

I'm working on a project with a similar structure, [hdltypes](https://github.com/ktbarrett/hdltypes), and want to step back and figure all the bits out before I get too far into the meat of the project and it gets harder to make large changes.
